import { useAuth } from "@/_core/hooks/useAuth";
import { JacShell } from "@/components/jac/JacShell";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { calculateBalance, getBudgetExecution } from "@/lib/jac-calculations";
import { ArrowDownRight, ArrowUpRight, Landmark, Plus, ReceiptText, WalletCards } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

const money = (value: number) => new Intl.NumberFormat("es-CO", { style: "currency", currency: "COP", maximumFractionDigits: 0 }).format(value);

export default function Finance() {
  const { isAuthenticated } = useAuth();
  const snapshot = trpc.finance.snapshot.useQuery(undefined, { enabled: isAuthenticated });
  const utils = trpc.useUtils();
  const [movementType, setMovementType] = useState<"ingreso" | "egreso">("egreso"); const [category, setCategory] = useState(""); const [description, setDescription] = useState(""); const [amount, setAmount] = useState(""); const [occurredAt, setOccurredAt] = useState(""); const [supportUrl, setSupportUrl] = useState("");
  const record = trpc.finance.record.useMutation({ onSuccess: async () => { await utils.finance.snapshot.invalidate(); setCategory(""); setDescription(""); setAmount(""); setSupportUrl(""); toast.success("Movimiento financiero registrado."); }, onError: error => toast.error(error.message) });
  const movements = snapshot.data?.movements ?? [];
  const income = movements.filter(item => item.movementType === "ingreso").reduce((total, item) => total + Number(item.amount), 0);
  const expenses = movements.filter(item => item.movementType === "egreso").reduce((total, item) => total + Number(item.amount), 0);
  const balance = calculateBalance(income, expenses);
  return <JacShell eyebrow="Tesorería y transparencia" title="Ingresos, gastos y balance" description="Registra caja menor, servicios, mantenimiento y aportes con soportes, categorías y trazabilidad para la rendición de cuentas.">
    <section className="grid gap-4 md:grid-cols-3"><FinanceCard icon={ArrowDownRight} label="Ingresos" value={money(income)} detail="Aportes, alquileres y actividades" tone="emerald" /><FinanceCard icon={ArrowUpRight} label="Egresos" value={money(expenses)} detail="Servicios, mantenimiento y caja menor" tone="rose" /><FinanceCard icon={WalletCards} label="Balance disponible" value={money(balance)} detail={`${movements.length} movimientos registrados`} tone="amber" /></section>
    <section className="mt-8 grid gap-6 xl:grid-cols-[.72fr_1.28fr]"><Card className="border-emerald-950/8 bg-white"><CardContent className="p-6"><p className="font-serif text-2xl font-bold text-emerald-950">Registrar movimiento</p><p className="mt-1 text-sm leading-6 text-emerald-950/55">El Tesorero, Fiscal o Directiva puede registrar movimientos con evidencia enlazada.</p>{isAuthenticated ? <form onSubmit={event => { event.preventDefault(); record.mutate({ movementType, category, description, amount, occurredAt: new Date(occurredAt), supportUrl: supportUrl || null, activityId: null }); }} className="mt-6 grid gap-4"><select value={movementType} onChange={event => setMovementType(event.target.value as "ingreso" | "egreso")} className="h-10 rounded-xl border border-emerald-950/15 bg-white px-3 text-sm"><option value="egreso">Egreso</option><option value="ingreso">Ingreso</option></select><Input value={category} onChange={e => setCategory(e.target.value)} placeholder="Categoría: servicios, aporte, mantenimiento…" required className="rounded-xl border-emerald-950/15" /><Textarea value={description} onChange={e => setDescription(e.target.value)} placeholder="Descripción del movimiento" required className="min-h-24 rounded-xl border-emerald-950/15" /><div className="grid grid-cols-2 gap-3"><Input value={amount} onChange={e => setAmount(e.target.value)} inputMode="decimal" placeholder="Valor COP" required className="rounded-xl border-emerald-950/15" /><Input type="date" value={occurredAt} onChange={e => setOccurredAt(e.target.value)} required className="rounded-xl border-emerald-950/15" /></div><Input value={supportUrl} onChange={e => setSupportUrl(e.target.value)} placeholder="URL del soporte (opcional)" className="rounded-xl border-emerald-950/15" /><Button disabled={record.isPending} className="rounded-xl bg-emerald-700 hover:bg-emerald-800"><Plus className="mr-2 h-4 w-4" />Registrar {movementType}</Button></form> : <AccessNote />}</CardContent></Card>
      <div className="grid gap-6"><Card className="border-emerald-950/8 bg-emerald-950 text-white"><CardContent className="p-6"><Landmark className="h-5 w-5 text-amber-200" /><p className="mt-5 font-serif text-2xl font-bold">Ejecución presupuestal</p><p className="mt-2 text-sm leading-6 text-emerald-50/70">El indicador se calcula al registrar el presupuesto aprobado para el periodo. Actualmente no hay presupuesto base cargado.</p><div className="mt-6 h-2 overflow-hidden rounded-full bg-white/15"><div className="h-full w-0 bg-amber-300" /></div><p className="mt-3 text-xs font-bold uppercase tracking-[.14em] text-emerald-100/70">{getBudgetExecution(expenses, 0)}% calculable sin presupuesto aprobado</p></CardContent></Card><Card className="border-emerald-950/8 bg-white"><CardContent className="p-0"><div className="border-b border-emerald-950/8 p-6"><p className="font-serif text-2xl font-bold text-emerald-950">Libro de caja reciente</p><p className="mt-1 text-sm text-emerald-950/55">Movimientos ordenados por fecha de registro.</p></div>{movements.length ? <div className="divide-y divide-emerald-950/8">{movements.map(item => <div key={item.id} className="flex items-center gap-4 p-5"><span className={`grid h-9 w-9 place-items-center rounded-xl ${item.movementType === "ingreso" ? "bg-emerald-100 text-emerald-800" : "bg-rose-100 text-rose-800"}`}>{item.movementType === "ingreso" ? <ArrowDownRight className="h-4 w-4" /> : <ArrowUpRight className="h-4 w-4" />}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold text-emerald-950">{item.category}</p><p className="truncate text-xs text-emerald-950/55">{item.description}</p></div><p className="text-sm font-bold text-emerald-950">{money(Number(item.amount))}</p></div>)}</div> : <div className="grid place-items-center px-6 py-14 text-center"><ReceiptText className="h-7 w-7 text-emerald-700" /><p className="mt-4 text-sm leading-6 text-emerald-950/60">No hay movimientos registrados. Registra el primer ingreso o egreso para actualizar el balance.</p></div>}</CardContent></Card></div></section>
  </JacShell>;
}
function FinanceCard({ icon: Icon, label, value, detail, tone }: { icon: typeof WalletCards; label: string; value: string; detail: string; tone: "emerald" | "rose" | "amber" }) { const color = { emerald: "bg-emerald-100 text-emerald-800", rose: "bg-rose-100 text-rose-800", amber: "bg-amber-100 text-amber-800" }[tone]; return <Card className="border-emerald-950/8 bg-white"><CardContent className="p-6"><span className={`grid h-10 w-10 place-items-center rounded-xl ${color}`}><Icon className="h-5 w-5" /></span><p className="mt-5 text-xs font-bold uppercase tracking-[.13em] text-emerald-950/55">{label}</p><p className="mt-1 font-serif text-2xl font-bold text-emerald-950">{value}</p><p className="mt-2 text-xs leading-5 text-emerald-950/55">{detail}</p></CardContent></Card>; }
function AccessNote() { return <div className="mt-6 rounded-xl bg-amber-50 p-4 text-sm leading-6 text-amber-950">Inicia sesión con un perfil autorizado para registrar movimientos de tesorería.</div>; }
