import { useAuth } from "@/_core/hooks/useAuth";
import { JacShell } from "@/components/jac/JacShell";
import { JacLoadingState } from "@/components/jac/JacLoadingState";
import { ObligationControl } from "@/components/jac/ObligationControl";
import { SupportFileInput } from "@/components/jac/SupportFileInput";
import { StatusBadge } from "@/components/jac/StatusBadge";
import { Button } from "@/components/ui/button";
import { Calendar } from "@/components/ui/calendar";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { CalendarClock, FileText, Landmark, Plus, Scale } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

const legalGuidance = [
  { title: "Plan de Desarrollo Comunal", reference: "Ley 2166 de 2021, artículo 46", detail: "La directiva debe presentarlo a consideración de la asamblea dentro de los 60 días calendario siguientes a su posesión.", entity: "Asamblea General" },
  { title: "Plan de Acción anual", reference: "Ley 2166 de 2021, artículo 46", detail: "La directiva elabora y presenta anualmente los planes de acción en concordancia con el plan aprobado.", entity: "Planeación municipal o distrital" },
  { title: "Rendición de cuentas", reference: "Ley 2166 de 2021, artículo 46", detail: "La directiva convoca una rendición de cuentas anual ante la asamblea general.", entity: "Asamblea General" },
  { title: "Informe anual de órganos", reference: "Ley 2166 de 2021, artículo 46", detail: "Se promueve una rendición anual de informes por cada órgano de la organización comunal.", entity: "Órganos de la JAC" },
];

const complianceTemplates = [
  { label: "Asamblea ordinaria", title: "Convocatoria a Asamblea General Ordinaria", type: "Asamblea reglamentaria", entity: "Asamblea General", reference: "Ley 2166 de 2021 y estatutos vigentes" },
  { label: "Rendición de cuentas", title: "Rendición anual de cuentas de la Directiva", type: "Rendición de cuentas", entity: "Asamblea General", reference: "Ley 2166 de 2021, artículo 46" },
  { label: "Informe IDPAC", title: "Presentación de informe institucional", type: "Reporte institucional", entity: "IDPAC / Alcaldía Local", reference: "Requerimiento de entidad competente y estatutos" },
];

export default function Obligations() {
  const { isAuthenticated, user } = useAuth();
  const snapshot = trpc.obligations.snapshot.useQuery(undefined, { enabled: isAuthenticated });
  const membersQuery = trpc.obligations.members.useQuery(undefined, { enabled: isAuthenticated });
  const utils = trpc.useUtils();
  const [title, setTitle] = useState(""); const [obligationType, setObligationType] = useState("Rendición de cuentas"); const [legalReference, setLegalReference] = useState("Ley 2166 de 2021, artículo 46"); const [receivingEntity, setReceivingEntity] = useState("Asamblea General"); const [recurrence, setRecurrence] = useState<"unica" | "anual" | "semestral" | "trimestral">("anual"); const [dueAt, setDueAt] = useState(""); const [notes, setNotes] = useState(""); const [supportUrl, setSupportUrl] = useState(""); const [responsibleUserId, setResponsibleUserId] = useState("");
  const create = trpc.obligations.create.useMutation({ onSuccess: async () => { await utils.obligations.snapshot.invalidate(); setTitle(""); setNotes(""); setSupportUrl(""); toast.success("Obligación registrada en el calendario."); }, onError: error => toast.error(error.message) });
  const applyTemplate = (template: typeof complianceTemplates[number]) => { setTitle(template.title); setObligationType(template.type); setReceivingEntity(template.entity); setLegalReference(template.reference); };
  const obligations = snapshot.data?.obligations ?? []; const members = membersQuery.data ?? [];
  if (snapshot.isLoading || membersQuery.isLoading) return <JacShell eyebrow="Cumplimiento y calendario" title="Matriz de obligaciones legales" description="Cargando obligaciones y fechas de cumplimiento."><JacLoadingState label="Cargando obligaciones" /></JacShell>;
  if (snapshot.error || membersQuery.error) return <JacShell eyebrow="Cumplimiento y calendario" title="Matriz de obligaciones legales" description="No fue posible consultar las obligaciones."><div role="alert" className="rounded-2xl border border-rose-200 bg-rose-50 p-6 text-sm text-rose-950">No se pudo cargar la matriz de obligaciones. Actualiza la página o intenta de nuevo.</div></JacShell>;
  return <JacShell eyebrow="Cumplimiento y calendario" title="Matriz de obligaciones legales" description="Un registro trazable para controlar convocatorias, rendición de cuentas, planes e informes ante la Asamblea y entidades competentes.">
    <section className="rounded-3xl border border-sky-200 bg-sky-50 p-6 sm:p-7"><div className="flex gap-4"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-white text-sky-800"><Scale className="h-5 w-5" /></span><div><p className="font-serif text-xl font-bold text-emerald-950">Base normativa de referencia</p><p className="mt-1 text-sm leading-6 text-emerald-950/65">La matriz traduce obligaciones institucionales en fechas, responsables y soportes. La configuración definitiva debe contrastarse con los estatutos vigentes y la autoridad competente.</p><a href="https://www.funcionpublica.gov.co/eva/gestornormativo/norma.php?i=184758" target="_blank" rel="noreferrer" className="mt-3 inline-flex text-sm font-bold text-emerald-800 hover:text-emerald-950">Consultar Ley 2166 de 2021</a></div></div></section>
    <section className="mt-8 grid gap-4 lg:grid-cols-2">{legalGuidance.map(item => <Card key={item.title} className="border-emerald-950/8 bg-white"><CardContent className="p-6"><div className="flex items-start justify-between gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-emerald-50 text-emerald-700"><Landmark className="h-4 w-4" /></span><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-[11px] font-bold text-emerald-800">{item.entity}</span></div><p className="mt-5 font-serif text-xl font-bold text-emerald-950">{item.title}</p><p className="mt-2 text-xs font-bold uppercase tracking-[.1em] text-emerald-700">{item.reference}</p><p className="mt-3 text-sm leading-6 text-emerald-950/62">{item.detail}</p></CardContent></Card>)}</section>
    <section className="mt-8 rounded-2xl border border-amber-200 bg-amber-50 p-5"><p className="text-xs font-bold uppercase tracking-[.12em] text-amber-900">Plantillas de cumplimiento</p><p className="mt-1 text-sm text-amber-950/75">Carga una plantilla para fijar título, referencia y entidad receptora; luego define responsable y fecha aplicable.</p><div className="mt-4 flex flex-wrap gap-2">{complianceTemplates.map(template => <Button key={template.label} type="button" variant="outline" onClick={() => applyTemplate(template)} className="rounded-xl border-amber-300 bg-white text-amber-950 hover:bg-amber-100">{template.label}</Button>)}</div></section>
    <section className="mt-6 grid gap-6 xl:grid-cols-[.72fr_1.28fr]"><Card className="border-emerald-950/8 bg-white"><CardContent className="p-6"><p className="font-serif text-2xl font-bold text-emerald-950">Calendarizar obligación</p><p className="mt-1 text-sm leading-6 text-emerald-950/55">Asigna fecha, responsable, entidad receptora, periodicidad y evidencia de cumplimiento.</p>{isAuthenticated ? <form onSubmit={event => { event.preventDefault(); create.mutate({ title, obligationType, legalReference, receivingEntity: receivingEntity || null, recurrence, dueAt: new Date(dueAt), responsibleUserId: responsibleUserId ? Number(responsibleUserId) : user?.id ?? null, supportUrl: supportUrl || null, notes: notes || null }); }} className="mt-6 grid gap-4"><Input value={title} onChange={e => setTitle(e.target.value)} placeholder="Nombre de la obligación" required className="rounded-xl border-emerald-950/15" /><Input value={obligationType} onChange={e => setObligationType(e.target.value)} placeholder="Tipo de obligación" required className="rounded-xl border-emerald-950/15" /><Input value={legalReference} onChange={e => setLegalReference(e.target.value)} placeholder="Referencia normativa" required className="rounded-xl border-emerald-950/15" /><Input value={receivingEntity} onChange={e => setReceivingEntity(e.target.value)} placeholder="Entidad receptora" className="rounded-xl border-emerald-950/15" /><select value={responsibleUserId} onChange={e => setResponsibleUserId(e.target.value)} className="h-10 rounded-xl border border-emerald-950/15 bg-white px-3 text-sm"><option value="">Responsable: usuario actual</option>{members.map(member => <option key={member.id} value={member.id}>{member.name || member.email || `Usuario ${member.id}`} · {member.jacRole}</option>)}</select><div className="grid grid-cols-2 gap-3"><select value={recurrence} onChange={e => setRecurrence(e.target.value as typeof recurrence)} className="h-10 rounded-xl border border-emerald-950/15 bg-white px-3 text-sm"><option value="unica">Única</option><option value="anual">Anual</option><option value="semestral">Semestral</option><option value="trimestral">Trimestral</option></select><Input type="date" value={dueAt} onChange={e => setDueAt(e.target.value)} required className="rounded-xl border-emerald-950/15" /></div><Input value={supportUrl} onChange={e => setSupportUrl(e.target.value)} placeholder="URL de soporte (opcional)" className="rounded-xl border-emerald-950/15" /><SupportFileInput onUploaded={setSupportUrl} /><Textarea value={notes} onChange={e => setNotes(e.target.value)} placeholder="Notas de seguimiento" className="min-h-20 rounded-xl border-emerald-950/15" /><Button disabled={create.isPending} className="rounded-xl bg-emerald-700 hover:bg-emerald-800"><Plus className="mr-2 h-4 w-4" />Agregar al calendario</Button></form> : <AccessNote />}</CardContent></Card>
      <Card className="border-emerald-950/8 bg-white"><CardContent className="p-0"><div className="border-b border-emerald-950/8 p-6"><div className="flex items-center gap-3"><CalendarClock className="h-5 w-5 text-emerald-700" /><div><h2 className="font-serif text-2xl font-bold text-emerald-950">Calendario operativo</h2><p className="mt-1 text-sm text-emerald-950/55">Obligaciones con fecha, responsable, soporte y estado.</p></div></div></div>{obligations.length ? <div className="divide-y divide-emerald-950/8">{obligations.map(item => <div key={item.id} className="p-5"><div className="flex flex-wrap items-center gap-4"><FileText className="h-4 w-4 text-emerald-700" /><div className="min-w-48 flex-1"><p className="text-sm font-bold text-emerald-950">{item.title}</p><p className="mt-1 text-xs text-emerald-950/55">{item.legalReference} · {new Date(item.dueAt).toLocaleDateString("es-CO")}</p><p className="mt-1 text-[11px] font-semibold text-emerald-700">Responsable: {members.find(member => member.id === item.responsibleUserId)?.name || members.find(member => member.id === item.responsibleUserId)?.email || "Sin asignar"}</p></div><StatusBadge status={item.status} /></div>{isAuthenticated ? <ObligationControl obligation={item} /> : null}</div>)}</div> : <p className="p-8 text-center text-sm text-emerald-950/60">Aún no hay obligaciones calendarizadas. Registra la primera fecha de rendición, asamblea o informe.</p>}</CardContent></Card></section>
    <section className="mt-6"><Card className="border-emerald-950/8 bg-white"><CardContent className="grid gap-6 p-6 lg:grid-cols-[auto_1fr]"><Calendar mode="multiple" selected={obligations.map(item => new Date(item.dueAt))} className="rounded-2xl border border-emerald-950/10" /><div><p className="font-serif text-2xl font-bold text-emerald-950">Calendario mensual de vencimientos</p><p className="mt-2 text-sm leading-6 text-emerald-950/60">Los días resaltados corresponden a obligaciones registradas. Utiliza la navegación mensual para anticipar asambleas, rendiciones e informes.</p><div className="mt-5 flex flex-wrap gap-2"><span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-bold text-emerald-800">{obligations.length} fechas registradas</span><span className="rounded-full bg-amber-100 px-3 py-1 text-xs font-bold text-amber-900">IDPAC y Alcaldía se registran como entidad receptora</span></div></div></CardContent></Card></section>
  </JacShell>;
}
function AccessNote() { return <div className="mt-6 rounded-xl bg-amber-50 p-4 text-sm leading-6 text-amber-950">Inicia sesión con perfil autorizado para calendarizar obligaciones normativas.</div>; }
