import { useAuth } from "@/_core/hooks/useAuth";
import { JacShell } from "@/components/jac/JacShell";
import { StatusBadge } from "@/components/jac/StatusBadge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { CalendarClock, FileText, Landmark, Plus, Scale } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

const legalGuidance = [
  { title: "Plan de Desarrollo Comunal", reference: "Ley 2166 de 2021, artículo 46", detail: "La directiva debe presentarlo a consideración de la asamblea dentro de los 60 días calendario siguientes a su posesión.", entity: "Asamblea General" },
  { title: "Plan de Acción anual", reference: "Ley 2166 de 2021, artículo 46", detail: "La directiva elabora y presenta anualmente los planes de acción en concordancia con el plan aprobado.", entity: "Planeación municipal o distrital" },
  { title: "Rendición de cuentas", reference: "Ley 2166 de 2021, artículo 46", detail: "La directiva convoca una rendición de cuentas anual ante la asamblea general.", entity: "Asamblea General" },
  { title: "Informe anual de órganos", reference: "Ley 2166 de 2021, artículo 46", detail: "Se promueve una rendición anual de informes por cada órgano de la organización comunal.", entity: "Órganos de la JAC" },
];

export default function Obligations() {
  const { isAuthenticated } = useAuth();
  const snapshot = trpc.obligations.snapshot.useQuery(undefined, { enabled: isAuthenticated });
  const utils = trpc.useUtils();
  const [title, setTitle] = useState(""); const [obligationType, setObligationType] = useState("Rendición de cuentas"); const [legalReference, setLegalReference] = useState("Ley 2166 de 2021, artículo 46"); const [receivingEntity, setReceivingEntity] = useState("Asamblea General"); const [recurrence, setRecurrence] = useState<"unica" | "anual" | "semestral" | "trimestral">("anual"); const [dueAt, setDueAt] = useState(""); const [notes, setNotes] = useState("");
  const create = trpc.obligations.create.useMutation({ onSuccess: async () => { await utils.obligations.snapshot.invalidate(); setTitle(""); setNotes(""); toast.success("Obligación registrada en el calendario."); }, onError: error => toast.error(error.message) });
  const obligations = snapshot.data?.obligations ?? [];
  return <JacShell eyebrow="Cumplimiento y calendario" title="Matriz de obligaciones legales" description="Un registro trazable para controlar convocatorias, rendición de cuentas, planes e informes ante la Asamblea y entidades competentes.">
    <section className="rounded-3xl border border-sky-200 bg-sky-50 p-6 sm:p-7"><div className="flex gap-4"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-white text-sky-800"><Scale className="h-5 w-5" /></span><div><p className="font-serif text-xl font-bold text-emerald-950">Base normativa de referencia</p><p className="mt-1 text-sm leading-6 text-emerald-950/65">La matriz traduce obligaciones institucionales en fechas, responsables y soportes. La configuración definitiva debe contrastarse con los estatutos vigentes y la autoridad competente.</p><a href="https://www.funcionpublica.gov.co/eva/gestornormativo/norma.php?i=184758" target="_blank" rel="noreferrer" className="mt-3 inline-flex text-sm font-bold text-emerald-800 hover:text-emerald-950">Consultar Ley 2166 de 2021</a></div></div></section>
    <section className="mt-8 grid gap-4 lg:grid-cols-2">{legalGuidance.map(item => <Card key={item.title} className="border-emerald-950/8 bg-white"><CardContent className="p-6"><div className="flex items-start justify-between gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-emerald-50 text-emerald-700"><Landmark className="h-4 w-4" /></span><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-[11px] font-bold text-emerald-800">{item.entity}</span></div><p className="mt-5 font-serif text-xl font-bold text-emerald-950">{item.title}</p><p className="mt-2 text-xs font-bold uppercase tracking-[.1em] text-emerald-700">{item.reference}</p><p className="mt-3 text-sm leading-6 text-emerald-950/62">{item.detail}</p></CardContent></Card>)}</section>
    <section className="mt-8 grid gap-6 xl:grid-cols-[.72fr_1.28fr]"><Card className="border-emerald-950/8 bg-white"><CardContent className="p-6"><p className="font-serif text-2xl font-bold text-emerald-950">Calendarizar obligación</p><p className="mt-1 text-sm leading-6 text-emerald-950/55">Asigna fecha, entidad receptora y periodicidad para conservar la evidencia de cumplimiento.</p>{isAuthenticated ? <form onSubmit={event => { event.preventDefault(); create.mutate({ title, obligationType, legalReference, receivingEntity: receivingEntity || null, recurrence, dueAt: new Date(dueAt), responsibleUserId: null, notes: notes || null }); }} className="mt-6 grid gap-4"><Input value={title} onChange={e => setTitle(e.target.value)} placeholder="Nombre de la obligación" required className="rounded-xl border-emerald-950/15" /><Input value={obligationType} onChange={e => setObligationType(e.target.value)} placeholder="Tipo de obligación" required className="rounded-xl border-emerald-950/15" /><Input value={legalReference} onChange={e => setLegalReference(e.target.value)} placeholder="Referencia normativa" required className="rounded-xl border-emerald-950/15" /><Input value={receivingEntity} onChange={e => setReceivingEntity(e.target.value)} placeholder="Entidad receptora" className="rounded-xl border-emerald-950/15" /><div className="grid grid-cols-2 gap-3"><select value={recurrence} onChange={e => setRecurrence(e.target.value as typeof recurrence)} className="h-10 rounded-xl border border-emerald-950/15 bg-white px-3 text-sm"><option value="unica">Única</option><option value="anual">Anual</option><option value="semestral">Semestral</option><option value="trimestral">Trimestral</option></select><Input type="date" value={dueAt} onChange={e => setDueAt(e.target.value)} required className="rounded-xl border-emerald-950/15" /></div><Textarea value={notes} onChange={e => setNotes(e.target.value)} placeholder="Notas o soporte pendiente" className="min-h-20 rounded-xl border-emerald-950/15" /><Button disabled={create.isPending} className="rounded-xl bg-emerald-700 hover:bg-emerald-800"><Plus className="mr-2 h-4 w-4" />Agregar al calendario</Button></form> : <AccessNote />}</CardContent></Card>
      <Card className="border-emerald-950/8 bg-white"><CardContent className="p-0"><div className="border-b border-emerald-950/8 p-6"><div className="flex items-center gap-3"><CalendarClock className="h-5 w-5 text-emerald-700" /><div><h2 className="font-serif text-2xl font-bold text-emerald-950">Calendario operativo</h2><p className="mt-1 text-sm text-emerald-950/55">Obligaciones con fecha y estado de cumplimiento.</p></div></div></div>{obligations.length ? <div className="divide-y divide-emerald-950/8">{obligations.map(item => <div key={item.id} className="flex flex-wrap items-center gap-4 p-5"><FileText className="h-4 w-4 text-emerald-700" /><div className="min-w-48 flex-1"><p className="text-sm font-bold text-emerald-950">{item.title}</p><p className="mt-1 text-xs text-emerald-950/55">{item.legalReference} · {new Date(item.dueAt).toLocaleDateString("es-CO")}</p></div><StatusBadge status={item.status} /></div>)}</div> : <p className="p-8 text-center text-sm text-emerald-950/60">Aún no hay obligaciones calendarizadas. Registra la primera fecha de rendición, asamblea o informe.</p>}</CardContent></Card></section>
  </JacShell>;
}
function AccessNote() { return <div className="mt-6 rounded-xl bg-amber-50 p-4 text-sm leading-6 text-amber-950">Inicia sesión con perfil autorizado para calendarizar obligaciones normativas.</div>; }
